name: CI

on: push

jobs:
  ci:
    strategy:
      matrix:
        os:
          - macOS-10.14
    steps:
      - uses: actions/checkout@master
      - run: env | sort
      - run: pwd
      - run: ls -all
